Author: <br>
Naoki Atkins <br>

In this hw assignment, we are looking at how different classifiers will perform on a real world dataset. First, we trained all of the classifiers on the original dataset. But then, we realized that the dataset consisted of an uneven amount of target values (too many no's in the dataset) so we resampled and retrained our classifiers.

***Question 2***

In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score
from imblearn.over_sampling import RandomOverSampler 

In [2]:
bank = pd.read_csv("./bank-additional/bank-additional.csv", sep=";")
bank

age          job  marital          education default  housing     loan  \
0      30  blue-collar  married           basic.9y      no      yes       no   
1      39     services   single        high.school      no       no       no   
2      25     services  married        high.school      no      yes       no   
3      38     services  married           basic.9y      no  unknown  unknown   
4      47       admin.  married  university.degree      no      yes       no   
...   ...          ...      ...                ...     ...      ...      ...   
4114   30       admin.  married           basic.6y      no      yes      yes   
4115   39       admin.  married        high.school      no      yes       no   
4116   27      student   single        high.school      no       no       no   
4117   58       admin.  married        high.school      no       no       no   
4118   34   management   single        high.school      no      yes       no   

        contact month day_of_week  ...  campaign  pdays  previous  \
0      cellular   may         fri  ...         2    999         0   
1     telephone   may         fri  ...         4    999         0   
2     telephone   jun         wed  ...         1    999         0   
3     telephone   jun         fri  ...         3    999         0   
4      cellular   nov         mon  ...         1    999         0   
...         ...   ...         ...  ...       ...    ...       ...   
4114   cellular   jul         thu  ...         1    999         0   
4115  telephone   jul         fri  ...         1    999         0   
4116   cellular   may         mon  ...         2    999         1   
4117   cellular   aug         fri  ...         1    999         0   
4118   cellular   nov         wed  ...         1    999         0   

         poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0     nonexistent         -1.8          92.893          -46.2      1.313   
1     nonexistent          1.1          93.994          -36.4      4.855   
2     nonexistent          1.4          94.465          -41.8      4.962   
3     nonexistent          1.4          94.465          -41.8      4.959   
4     nonexistent         -0.1          93.200          -42.0      4.191   
...           ...          ...             ...            ...        ...   
4114  nonexistent          1.4          93.918          -42.7      4.958   
4115  nonexistent          1.4          93.918          -42.7      4.959   
4116      failure         -1.8          92.893          -46.2      1.354   
4117  nonexistent          1.4          93.444          -36.1      4.966   
4118  nonexistent         -0.1          93.200          -42.0      4.120   

      nr.employed   y  
0          5099.1  no  
1          5191.0  no  
2          5228.1  no  
3          5228.1  no  
4          5195.8  no  
...           ...  ..  
4114       5228.1  no  
4115       5228.1  no  
4116       5099.1  no  
4117       5228.1  no  
4118       5195.8  no  

[4119 rows x 21 columns]

***Question 3a***

In [3]:
bank = pd.get_dummies(bank, drop_first=True)
bank

age  duration  campaign  pdays  previous  emp.var.rate  cons.price.idx  \
0      30       487         2    999         0          -1.8          92.893   
1      39       346         4    999         0           1.1          93.994   
2      25       227         1    999         0           1.4          94.465   
3      38        17         3    999         0           1.4          94.465   
4      47        58         1    999         0          -0.1          93.200   
...   ...       ...       ...    ...       ...           ...             ...   
4114   30        53         1    999         0           1.4          93.918   
4115   39       219         1    999         0           1.4          93.918   
4116   27        64         2    999         1          -1.8          92.893   
4117   58       528         1    999         0           1.4          93.444   
4118   34       175         1    999         0          -0.1          93.200   

      cons.conf.idx  euribor3m  nr.employed  ...  month_nov  month_oct  \
0             -46.2      1.313       5099.1  ...          0          0   
1             -36.4      4.855       5191.0  ...          0          0   
2             -41.8      4.962       5228.1  ...          0          0   
3             -41.8      4.959       5228.1  ...          0          0   
4             -42.0      4.191       5195.8  ...          1          0   
...             ...        ...          ...  ...        ...        ...   
4114          -42.7      4.958       5228.1  ...          0          0   
4115          -42.7      4.959       5228.1  ...          0          0   
4116          -46.2      1.354       5099.1  ...          0          0   
4117          -36.1      4.966       5228.1  ...          0          0   
4118          -42.0      4.120       5195.8  ...          1          0   

      month_sep  day_of_week_mon  day_of_week_thu  day_of_week_tue  \
0             0                0                0                0   
1             0                0                0                0   
2             0                0                0                0   
3             0                0                0                0   
4             0                1                0                0   
...         ...              ...              ...              ...   
4114          0                0                1                0   
4115          0                0                0                0   
4116          0                1                0                0   
4117          0                0                0                0   
4118          0                0                0                0   

      day_of_week_wed  poutcome_nonexistent  poutcome_success  y_yes  
0                   0                     1                 0      0  
1                   0                     1                 0      0  
2                   1                     1                 0      0  
3                   0                     1                 0      0  
4                   0                     1                 0      0  
...               ...                   ...               ...    ...  
4114                0                     1                 0      0  
4115                0                     1                 0      0  
4116                0                     0                 0      0  
4117                0                     1                 0      0  
4118                1                     1                 0      0  

[4119 rows x 54 columns]

***Question 3b***

In [4]:
bank = bank.drop(columns = 'duration')
bank

age  campaign  pdays  previous  emp.var.rate  cons.price.idx  \
0      30         2    999         0          -1.8          92.893   
1      39         4    999         0           1.1          93.994   
2      25         1    999         0           1.4          94.465   
3      38         3    999         0           1.4          94.465   
4      47         1    999         0          -0.1          93.200   
...   ...       ...    ...       ...           ...             ...   
4114   30         1    999         0           1.4          93.918   
4115   39         1    999         0           1.4          93.918   
4116   27         2    999         1          -1.8          92.893   
4117   58         1    999         0           1.4          93.444   
4118   34         1    999         0          -0.1          93.200   

      cons.conf.idx  euribor3m  nr.employed  job_blue-collar  ...  month_nov  \
0             -46.2      1.313       5099.1                1  ...          0   
1             -36.4      4.855       5191.0                0  ...          0   
2             -41.8      4.962       5228.1                0  ...          0   
3             -41.8      4.959       5228.1                0  ...          0   
4             -42.0      4.191       5195.8                0  ...          1   
...             ...        ...          ...              ...  ...        ...   
4114          -42.7      4.958       5228.1                0  ...          0   
4115          -42.7      4.959       5228.1                0  ...          0   
4116          -46.2      1.354       5099.1                0  ...          0   
4117          -36.1      4.966       5228.1                0  ...          0   
4118          -42.0      4.120       5195.8                0  ...          1   

      month_oct  month_sep  day_of_week_mon  day_of_week_thu  day_of_week_tue  \
0             0          0                0                0                0   
1             0          0                0                0                0   
2             0          0                0                0                0   
3             0          0                0                0                0   
4             0          0                1                0                0   
...         ...        ...              ...              ...              ...   
4114          0          0                0                1                0   
4115          0          0                0                0                0   
4116          0          0                1                0                0   
4117          0          0                0                0                0   
4118          0          0                0                0                0   

      day_of_week_wed  poutcome_nonexistent  poutcome_success  y_yes  
0                   0                     1                 0      0  
1                   0                     1                 0      0  
2                   1                     1                 0      0  
3                   0                     1                 0      0  
4                   0                     1                 0      0  
...               ...                   ...               ...    ...  
4114                0                     1                 0      0  
4115                0                     1                 0      0  
4116                0                     0                 0      0  
4117                0                     1                 0      0  
4118                1                     1                 0      0  

[4119 rows x 53 columns]

In [5]:
target = bank['y_yes']
bank = bank.drop(columns = 'y_yes')
bank

age  campaign  pdays  previous  emp.var.rate  cons.price.idx  \
0      30         2    999         0          -1.8          92.893   
1      39         4    999         0           1.1          93.994   
2      25         1    999         0           1.4          94.465   
3      38         3    999         0           1.4          94.465   
4      47         1    999         0          -0.1          93.200   
...   ...       ...    ...       ...           ...             ...   
4114   30         1    999         0           1.4          93.918   
4115   39         1    999         0           1.4          93.918   
4116   27         2    999         1          -1.8          92.893   
4117   58         1    999         0           1.4          93.444   
4118   34         1    999         0          -0.1          93.200   

      cons.conf.idx  euribor3m  nr.employed  job_blue-collar  ...  month_may  \
0             -46.2      1.313       5099.1                1  ...          1   
1             -36.4      4.855       5191.0                0  ...          1   
2             -41.8      4.962       5228.1                0  ...          0   
3             -41.8      4.959       5228.1                0  ...          0   
4             -42.0      4.191       5195.8                0  ...          0   
...             ...        ...          ...              ...  ...        ...   
4114          -42.7      4.958       5228.1                0  ...          0   
4115          -42.7      4.959       5228.1                0  ...          0   
4116          -46.2      1.354       5099.1                0  ...          1   
4117          -36.1      4.966       5228.1                0  ...          0   
4118          -42.0      4.120       5195.8                0  ...          0   

      month_nov  month_oct  month_sep  day_of_week_mon  day_of_week_thu  \
0             0          0          0                0                0   
1             0          0          0                0                0   
2             0          0          0                0                0   
3             0          0          0                0                0   
4             1          0          0                1                0   
...         ...        ...        ...              ...              ...   
4114          0          0          0                0                1   
4115          0          0          0                0                0   
4116          0          0          0                1                0   
4117          0          0          0                0                0   
4118          1          0          0                0                0   

      day_of_week_tue  day_of_week_wed  poutcome_nonexistent  poutcome_success  
0                   0                0                     1                 0  
1                   0                0                     1                 0  
2                   0                1                     1                 0  
3                   0                0                     1                 0  
4                   0                0                     1                 0  
...               ...              ...                   ...               ...  
4114                0                0                     1                 0  
4115                0                0                     1                 0  
4116                0                0                     0                 0  
4117                0                0                     1                 0  
4118                0                1                     1                 0  

[4119 rows x 52 columns]

***Question 3c***

In [6]:
cols_to_std = ['age', 'campaign', 'pdays', 'previous', 'emp.var.rate', 'cons.price.idx', 
                   'cons.conf.idx', 'euribor3m', 'nr.employed']

df_to_scale = bank[cols_to_std]

df_to_remain = bank.iloc[:,9:]

scaler = preprocessing.StandardScaler()
scaler = scaler.fit(df_to_scale)
scaled_df = scaler.transform(df_to_scale)

scaled_df = pd.DataFrame(scaled_df, columns = cols_to_std)

df = pd.concat([scaled_df, df_to_remain], axis = 1)
df

age  campaign     pdays  previous  emp.var.rate  cons.price.idx  \
0    -0.980752 -0.209228  0.201031 -0.351356     -1.206054       -1.185448   
1    -0.107991  0.569634  0.201031 -0.351356      0.649441        0.715193   
2    -1.465619 -0.598660  0.201031 -0.351356      0.841389        1.528273   
3    -0.204965  0.180203  0.201031 -0.351356      0.841389        1.528273   
4     0.667795 -0.598660  0.201031 -0.351356     -0.118350       -0.655478   
...        ...       ...       ...       ...           ...             ...   
4114 -0.980752 -0.598660  0.201031 -0.351356      0.841389        0.583995   
4115 -0.107991 -0.598660  0.201031 -0.351356      0.841389        0.583995   
4116 -1.271672 -0.209228  0.201031  1.494607     -1.206054       -1.185448   
4117  1.734503 -0.598660  0.201031 -0.351356      0.841389       -0.234264   
4118 -0.592858 -0.598660  0.201031 -0.351356     -0.118350       -0.655478   

      cons.conf.idx  euribor3m  nr.employed  job_blue-collar  ...  month_may  \
0         -1.240939  -1.331707    -0.914779                1  ...          1   
1          0.892269   0.711698     0.332862                0  ...          1   
2         -0.283172   0.773427     0.836535                0  ...          0   
3         -0.283172   0.771697     0.836535                0  ...          0   
4         -0.326707   0.328632     0.398028                0  ...          0   
...             ...        ...          ...              ...  ...        ...   
4114      -0.479079   0.771120     0.836535                0  ...          0   
4115      -0.479079   0.771697     0.836535                0  ...          0   
4116      -1.240939  -1.308054    -0.914779                0  ...          1   
4117       0.957571   0.775735     0.836535                0  ...          0   
4118      -0.326707   0.287672     0.398028                0  ...          0   

      month_nov  month_oct  month_sep  day_of_week_mon  day_of_week_thu  \
0             0          0          0                0                0   
1             0          0          0                0                0   
2             0          0          0                0                0   
3             0          0          0                0                0   
4             1          0          0                1                0   
...         ...        ...        ...              ...              ...   
4114          0          0          0                0                1   
4115          0          0          0                0                0   
4116          0          0          0                1                0   
4117          0          0          0                0                0   
4118          1          0          0                0                0   

      day_of_week_tue  day_of_week_wed  poutcome_nonexistent  poutcome_success  
0                   0                0                     1                 0  
1                   0                0                     1                 0  
2                   0                1                     1                 0  
3                   0                0                     1                 0  
4                   0                0                     1                 0  
...               ...              ...                   ...               ...  
4114                0                0                     1                 0  
4115                0                0                     1                 0  
4116                0                0                     0                 0  
4117                0                0                     1                 0  
4118                0                1                     1                 0  

[4119 rows x 52 columns]

***Question 4***

In [7]:
gnb = GaussianNB()
gnb.fit(df, target)
print(gnb.score(df, target))

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(df, target)
print(knn.score(df, target))

svm = make_pipeline(StandardScaler(), SVC(gamma='auto'))
svm.fit(df, target)
print(svm.score(df, target))

0.5906773488710853
0.9235251274581209
0.9184268026219956


***Question 5***

In [8]:
target.value_counts()

0    3668
1     451
Name: y_yes, dtype: int64

451 yes, 3668 no

3668 / (451 + 3668) = 0.89050740471

***Question 6***

In [9]:
dumb_target = np.zeros_like(target)
dumb_target.shape

(4119,)

In [10]:
confusion_matrix(target, dumb_target)

array([[3668,    0],
       [ 451,    0]])

In [11]:
roc_auc_score(target, dumb_target)

0.5

***Question 7***

In [12]:
confusion_matrix(target, gnb.predict(df))

array([[2083, 1585],
       [ 101,  350]])

In [13]:
confusion_matrix(target, knn.predict(df))

array([[3606,   62],
       [ 253,  198]])

In [14]:
confusion_matrix(target, svm.predict(df))

array([[3655,   13],
       [ 323,  128]])

***Question 8***

In [15]:
ros = RandomOverSampler(random_state=(2021-4-22))
df_resampled, target_resampled = ros.fit_resample(df, target)

***Question 9***

In [16]:
gnb = GaussianNB()
gnb.fit(df_resampled, target_resampled)
print(gnb.score(df_resampled, target_resampled))

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(df_resampled, target_resampled)
print(knn.score(df_resampled, target_resampled))

svm = make_pipeline(StandardScaler(), SVC(gamma='auto'))
svm.fit(df_resampled, target_resampled)
print(svm.score(df_resampled, target_resampled))

0.6529443838604144
0.9554252998909487
0.8797709923664122


In [17]:
confusion_matrix(target_resampled, gnb.predict(df_resampled))

array([[1818, 1850],
       [ 696, 2972]])

In [18]:
confusion_matrix(target_resampled, knn.predict(df_resampled))

array([[3341,  327],
       [   0, 3668]])

In [19]:
confusion_matrix(target_resampled, svm.predict(df_resampled))

array([[3322,  346],
       [ 536, 3132]])